### ISSUE TITLE
User processes keep running after logout

### ISSUE THREAD

**Issue by ArthurBorsboom** [lxqt/lxqt-session#331]
Steps to reproduce
------------------------------------------------------------------
User arthur logs in: SDDM + user/pass + session lxqt
User arthur logs out: Leave -> logout
SDDM is back at the login screen
No user is logged in anymore
Switch to tty2
Login as root
"ps aux | grep arthur" shows several processes which have been started during the lxqt session, but not stopped at logoff

------------------------------------------------------------------

See the attachment below of the processes which are still running after logoff.

The reason why I got to this point is the long shutdown time of the laptop (1-2 minutes), showing several processes still running.
Some of these processes blocking the shutdown are the same as the ones in the attachment, such as gvfs and friends.

------------------------------------------------------------------

##### System Information
* Distribution & Version: Arch Linux
* Kernel: 5.8.7
* Qt Version: 5.15.0
* liblxqt Version: 0.15.1
* lxqt packages: 0.15.0 / 0.15.1 

[lxqt-processes-after-logout.txt](https://github.com/lxqt/lxqt-session/files/5204948/lxqt-processes-after-logout.txt)

**Comment by tsujan** [comment]
/etc/systemd/logind.conf → KillUserProcesses

https://www.freedesktop.org/software/systemd/man/logind.conf.html#KillUserProcesses=

**Comment by ArthurBorsboom** [comment]
Thanks for the pointer.
Setting KillUserProcesses=yes solved the issue.

A bit surprising that I had to configure this explicitly, since 'it used to work'.

I am guessing the default had changed over time, since the default is documented differently.

Defaults to "yes": https://www.freedesktop.org/software/systemd/man/logind.conf.html#KillUserProcesses=
Defaults to "no": man logind.conf

**Comment by tsujan** [comment]
> A bit surprising that I had to configure this explicitly, since 'it used to work'.

Like what happened to me years ago. I've never been able to like systemd, although it has become much better than the mess it was before.

BTW, none of those processes belonged to LXQt; they may only have been called by LXQt components.
