### ISSUE TITLE
Localization place should be updated in README.md

### ISSUE THREAD

**Issue by pols12** [lxqt/lxqt-session#344]
Current README.md file links to [lxqt/lxqt-l10n](https://github.com/lxqt/lxqt-l10n) for localization, however this one is deprecated.

New link given in [lxqt/lxqt-l10n-deprecated](https://github.com/lxqt/lxqt-l10n-deprecated) README.md is down: https://weblate.lxqt.org This should be fixed with https://translate.lxqt-project.org.

This last translate place (translate.lxqt-project.org) doesn’t seem to contain files for lxqt-session. Only files for [lxqt-configuration/lxqt-session](https://translate.lxqt-project.org/projects/lxqt-configuration/lxqt-session/).

**Where can we add/update translations?** This should be shown in:
* [lxqt/lxqt-l10n-deprecated/README.md](https://github.com/lxqt/lxqt-l10n-deprecated)
* [lxqt/lxqt-session/README.md](https://github.com/lxqt/lxqt-session)

**Comment by tsujan** [comment]
Already taken care by @stefonarch: https://github.com/lxqt/lxqt-session/pull/342

**Comment by stefonarch** [comment]
> **Where can we add/update translations?** This should be shown in:
> 
> * [lxqt/lxqt-l10n-deprecated/README.md](https://github.com/lxqt/lxqt-l10n-deprecated)
> * [lxqt/lxqt-session/README.md](https://github.com/lxqt/lxqt-session)

Well, it _is_ shown: https://github.com/lxqt/lxqt-session#components
Further information: https://github.com/lxqt/lxqt/wiki/Translation

lxqt-l10n is read-only and there will be no additional information. 
Will merge the leftover PRs

**Comment by pols12** [comment]
> Well, it _is_ shown: https://github.com/lxqt/lxqt-session#components

Yes, I didn’t see that first, because of dead link. Since it’s removed now, we probably find the right place easier. Thanks! 🙂

> lxqt-l10n is read-only and there will be no additional information.

😞 It’s a shame this repo is blocked without pointing toward its replacement.

**Comment by stefonarch** [comment]
>  It’s a shame this repo is blocked without pointing toward its replacement.

No shame, just lack of manpower. And it's deprecated  some years now afaik.
