### ISSUE TITLE
Tooltips not shown for default folders

### ISSUE THREAD

**Issue by stefonarch** [lxqt/lxqt-session#357]
None of those https://github.com/lxqt/lxqt-session/blob/master/lxqt-config-session/userlocationspage.cpp/#L73 are seen on mousover in Session Settings → User directories.

##### Expected Behavior

Tooltips are present and often translated so they should be shown.
##### Current Behavior

They aren't.

I remember vaguely this issue, but it was translations missing probably.
                                     
* Distribution & Version: all & all

**Comment by tsujan** [comment]
They're all shown here:

![tooltip](https://user-images.githubusercontent.com/981076/104125140-1a6e3100-536a-11eb-9cd2-de883c1d5740.png)

But I don't include translations when compiling most LXQt components. Will recompile it with translations soon.

**Comment by stefonarch** [comment]
My mistake, there **are** shown on the file path, didn't wait enough time (at first it takes ~2 sec to show them).

**Comment by tsujan** [comment]
> at first it takes ~2 sec to show them

Oh, that's too long. It may be caused by the window manager or compositor you use.
