### ISSUE TITLE
Support for the use of qt5ct

### ISSUE THREAD

**Issue by 0n0w1c** [lxqt/lxqt-session#392]
startlxqt does not honor system setting of the QT_QPA_PLATFORMTHEME environment variable.

It would be helpful if the startlxqt script would check for a previous setting, and only set if not previously defined.
```
if [ -z "$QT_QPA_PLATFORMTHEME" ]; then
   export QT_QPA_PLATFORMTHEME=lxqt
fi
```
I have a use case for the use of QT_QPA_PLATFORMTHEME=qt5ct

**Comment by tsujan** [comment]
Understandably, `QT_QPA_PLATFORMTHEME` is `lxqt` in LXQt. You don't need and shouldn't use `qt5ct` under LXQt.
