### ISSUE TITLE
lxqt-config-session - under "Environment" page - text layout issue

### ISSUE THREAD

**Issue by ianfarrell47** [lxqt/lxqt-session#421]
**Issue**
Text of list item header is cut-off no matter the window size (for big enough fonts)

**Expected behavior**
When the window is first opened, there is room for displaying all list item headers completely.

lxqt-session-git 1.0.1.14.g5f2cf72 5f2cf72
qt5-base version: 5.15.3+kde+r133-1
Qt5 theme: Fusion

![lxqt-config-session](https://user-images.githubusercontent.com/96850319/157886616-c5f13049-da23-4e8e-975a-5bcdacc0cab5.png)

**Comment by tsujan** [comment]
Thanks for reporting! We will look into it.
