### ISSUE TITLE
Modules state not displayed after resume under wayland

### ISSUE THREAD

**Issue by stefonarch** [lxqt/lxqt-session#455]
It's some time now that module state after suspend isn't displayed anymore under wayland.
At login it works as usual.

![screen_window_dom_10:02:53_](https://user-images.githubusercontent.com/10681413/208289790-83e20de6-d2de-4984-80b9-e753d8e794cc.png)

```

$ lxqt-config-session 
QObject::connect: 
No such signal QDBusAbstractInterface::moduleStateChanged(QString,bool) 
in /home/stef/git/lxqt/lxqt-session/lxqt-config-session/modulemodel.cpp:39

```

##### Steps to Reproduce (for bugs)

1.  Start lxqt-session under wayland
2. Suspend
3.  After resume open lxqt-config-session

##### System Information

* Distribution & Version:  arch, latest git

**Comment by tsujan** [comment]
Are you sure it happens only under Wayland?

**Comment by stefonarch** [comment]
Just tested, it doesn't happen under X11.

**Comment by stefonarch** [comment]
Duplicate of https://github.com/lxqt/lxqt-session/issues/457
