### ISSUE TITLE
Name can not be missed when we want to add an autostart program

### ISSUE THREAD

**Issue by willemijns** [lxqt/lxqt-session#486]
Hello,

A cosmetic big on lqxt 0.17.0 used on Lubuntu

On session setting / autostart
Adding a command without a name does nothing after clicking on "ok" button...

In fact, if we want to add a program, we need to mandatory type a name ! 

So bug is only to indicate "name field can not be empty" if name is empty when we decide to click on OK button ;)

**Comment by tsujan** [comment]
> In short: both "Name" and "Command" textedits should be mandatory.

I agree.
