### ISSUE TITLE
docs, manual: describe the difference between the options "kwin" and "kwin_x11"

### ISSUE THREAD

**Issue by lorn10** [lxqt/lxqt-session#502]
Hi all

Here follows a request regarding the improvement of the Lubuntu docs / user manual.

I have searched quite intensively but wasn't able to find any more detailed information about the difference between the **kwin** and **kwin_x11** option in conjunction with the windowing manager.

Has this some relation to any sort of hardware acceleration? While the kwin option is listed as the first one most "recommendations" across the web prefer to chose kwin_x11. (Without explaining anything.)

I have tested both variants and didn't notice any difference.

This topic may became even more relevant in the future when Wayland will be officially supported in LXQT. Probably this would require a further third kwin option. :wink: 

Final note, when the docs are updated it might be useful to add also somewhere the information about the possibility to enable the OpenGL ES / EGL support in kwin. This might improve the overall behavior especially on ancient systems with no support of OGL3 and higher.

`sudo nano /etc/profile.d/kwin.sh`

add there:

`export KWIN_COMPOSE=O2ES`

More information can be found in [KDE bug 442386](https://bugs.kde.org/show_bug.cgi?id=442386).

And perhaps it would be also useful to check the [Mesa MR 9989](https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/9989) about an important EGL on X11 limitation.

**Comment by tsujan** [comment]
> Here follows a request regarding the improvement of the Lubuntu docs / user manual.

Should be sent to Lubuntu.

**Comment by lorn10** [comment]
Yeah I see, the Lubuntu docs should be updated. But this is also true regarding the[ LXQT Wiki](https://github.com/lxqt/lxqt/wiki/)?

The best thing would be if someone from LXQT could give here a simple answer what's difference is between "kwin" and "kwin_x11". :+1: 

My latest assumption is that "kwin_x11" may be something similar to the former XRender in KDE.

**Comment by tsujan** [comment]
It's distro-specific. In Arch, Manjaro and perhaps other Arch-based systems, there's no `kwin` but a `kwin_wayland` and a `kwin_x11` (whose names are self-explanatory). In Debian and its derivatives, they've added `/usr/bin/kwin` as a symlink to `/usr/bin/kwin_x11`.

BTW, we have https://github.com/lxqt/lxqt/discussions, which can be used for questions.
