### ISSUE TITLE
Add a method to disable autostarting for applications under wayland

### ISSUE THREAD

**Issue by stefonarch** [lxqt/lxqt-session#515]
Applications  which should start only in wayland can be added in the compositor's settings, but there is no way without scripts to achieve the opposite. 

We should not start under wayland 
* lxqt-globalkeys module (does no harm but is misleading)
* xscreensaver (it works under xwayland but can't lock which is expected)

There are other applications like redshift which could cause trouble, and some like qlipper which just won't work under wayland.

##### Possible Solution

![immagine](https://github.com/lxqt/lxqt-session/assets/10681413/c9656b35-5263-4b71-b3d9-2fe4253cf7cf)

And something like `X-LXQt-X11-Only=true`  or `X-LXQt-Wayland=false` in the desktopfile, including the ones we're shipping. @palinek ?

##### Context

Switching between X11 and wayland needs some scripts to achieve this, getting rid of them is mandatory for average users.

**Comment by stefonarch** [comment]
In `lxqtmodman.cpp` excluding files with`X-LXQt-X11-Only=true` looks working fine
```
void LXQtModuleManager::startAutostartApps()
{
    // XDG autostart
    const XdgDesktopFileList fileList = XdgAutoStart::desktopFileList();
    QList<const XdgDesktopFile*> trayApps;
    for (XdgDesktopFileList::const_iterator i = fileList.constBegin(); i != fileList.constEnd(); ++i)
        {
        if (i->value(QSL("X-LXQt-X11-Only"), false).toBool())
        {
        // Don't include those desktop files
        continue;
        }
        if (i->value(QSL("X-LXQt-Need-Tray"), false).toBool())
            trayApps.append(&(*i));
        else
        {
            startProcess(*i);
            qCDebug(SESSION) << "start" << i->fileName();
        }
    }
```
This needs 
1. The GUI as above in the screenshot
2. Adding the key in https://github.com/lxqt/lxqt-session/blob/master/autostart/lxqt-xscreensaver-autostart.desktop.in and in the .desktop file of lxqt-globalshortkeys.

**Comment by palinek** [comment]
Why adding a new special field? Can't we use the existing `OnlyShowIn, NotShowIn` ?

**Comment by stefonarch** [comment]
> Why adding a new special field? Can't we use the existing `OnlyShowIn, NotShowIn` ?

Sorry missed that comment. Didn't think about that, could work well using `NotShowIn=wayland` but that is not standard of that key probably:

> The NotShowIn field is a list of strings identifying the environments that should not display a given menu item. If an NotShowIn field is present, a given environment should only display the menu item if the string identifying that environment is not present. The strings are case-sensitive. [Appendix B, Registered OnlyShowIn Environments](https://specifications.freedesktop.org/menu-spec/latest/apb.html) enumerates the strings to use for some common environments.

**Comment by stefonarch** [comment]
Added `NotShowIn=wayland` and
```
$ desktop-file-validate /etc/xdg/autostart/lxqt-globalkeyshortcuts.desktop 
/etc/xdg/autostart/lxqt-globalkeyshortcuts.desktop: error: only one of "OnlyShowIn" and "NotShowIn" keys may appear in group "Desktop Entry"
/etc/xdg/autostart/lxqt-globalkeyshortcuts.desktop: error: value "wayland" for key "NotShowIn" in group "Desktop Entry" contains an unregistered value "wayland"; values extending the format should start with "X-"
```
