### ISSUE TITLE
Set a default QT_QUICK_CONTROLS_STYLE

### ISSUE THREAD

**Issue by antis81** [lxqt/lxqt-session#554]
Followup issue on [lxqt-wayland-session issue #31](https://github.com/lxqt/lxqt-wayland-session/issues/31).

Consider adding `QT_QUICK_CONTROLS_STYLE=org.kde.desktop` to `session.conf` as a "sane default" ([here](https://github.com/lxqt/lxqt-session/blob/005248bad8968ff98f2046c7c439596a1d24a20f/config/session.conf#L4)).

This improves theming issues on "fresh" LXQt installs providing a better "out-of-box" experience for our users.

In addition to that a system default will be nice - somewhere in the same context as `QT_QPA…` var's.

**Comment by tsujan** [comment]
It isn't a special thing and can be added by the user.

As for theming, LXQt's default is that of Qt. As we don't add Breeze as the default theme, we shouldn't set that EV by default.

**Comment by antis81** [comment]
Sure… LXQt by itself is not a special thing (never has been)… :)

**Comment by tsujan** [comment]
> This is (quite literally) the default style.

It isn't. It's made by KDE devs to compensate for the damage to their platform integration after filling KDE with QML.

**Comment by antis81** [comment]
Don't you think this is a little over the top…!? Yeah… KDE did and does bad design decisions I know… (Qt is nothing better btw.).

In this case however KDE provides a fix that works for many users and all we have to do is use it…

(When we look further at GTK 2 vs 3 vs 4… situation is not very much different…)
